Initial work on hash table implementation
Hash table created using an internet tutorial, kept to its own files so
it can be easily replaced later with something more...competent.

Does not build due to the following error:
/usr/bin/ld: src/common/libhexchatcommon.a(hashtable.c.o): undefined reference to symbol 'pow@@GLIBC_2.2.5'
This seems, from Google results, to be because of incorrect compiler
flags. Investigating fix.